#!/bin/bash
$config=$1

BUILD_DIR="./_out/build"
INSTALL_DIR="./_out/install"

if [ $config == "-r" ]; then
    cmake --install $BUILD_DIR/release --prefix $INSTALL_DIR/release --config Release
else
    cmake --install $BUILD_DIR/debug --prefix $INSTALL_DIR/debug --config Debug
fi

